---
title: "Ordinal scales and disease progression - theory"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(patchwork)
theme_set(theme_minimal())
```

```{r}

#bounded_sigmoid <- 

func_data <- function(f, label) {
    f_data <- data.frame(time = seq(0,1, length.out = 1000), label = label)
    f_data$f <- f(f_data$time)
    
    N_thres <- 20
    tt_base <- (-1 + 1/seq(0.025,0.95, length.out = N_thres))^0.5
    # threshold_targets <- qnorm(seq(0.001,0.999, length.out = N_thres))
    # threshold_targets <- 0.025 + (threshold_targets - min(threshold_targets)) * 0.95 / (max(threshold_targets) - min(threshold_targets))
    threshold_targets <- tt_base / (1 + tt_base)
    thresholds <-  f(threshold_targets)
    
    observed <- data.frame(time = f_data$time, score = purrr::map_int(f_data$f, ~ sum(thresholds < .x)),
                           label = label)
    
    
    list(true = f_data, observed = observed, thresholds = data.frame(threshold = thresholds, label = label))
}

all_func_data <- list(
    func_data(function(x) 1-x, "Uniform"),
    func_data(function(x) { 1 / (1 + (1/x - 1) ^ -2) }, "Sigmoid"),
    func_data(function(x) 1 - x^2.5, "Accelerating"),
    func_data(function(x) 1 - x^(0.55), "Deccelerating")
) 

label_to_fct <- function(x) {
    mutate(x, label = factor(label, levels = c("Uniform", "Sigmoid", "Accelerating", "Deccelerating")))
}

all_true <- purrr::map_dfr(all_func_data, function(x) x$true) %>%  label_to_fct()
all_observed <- purrr::map_dfr(all_func_data, function(x) x$observed) %>%  label_to_fct()
all_thresholds <- purrr::map_dfr(all_func_data, function(x) x$thresholds) %>%  label_to_fct()


time_scale <- scale_x_continuous("Time", breaks = c())
facet <- facet_wrap(~label, nrow = 1)
p_progression <- ggplot(aes(x = time, y = f), data = all_true) + geom_line(linewidth = 2, color = "orangered") +
    geom_hline(aes(yintercept = threshold), data = all_thresholds, color = "darkgray") + time_scale +
    scale_y_continuous("Biological function", breaks = c(0,1), labels = c("Death", "No damage")) + facet

p_observed <- ggplot(aes(x= time, y = score), data = all_observed) + geom_line(color = "darkblue") + time_scale + facet +
    scale_y_continuous("Score")

p_progression / p_observed

```

```{r}
N_questions <- 12
N_cat <- 5
alpha <- 1

max_score <- N_questions * (N_cat - 1)
thresholds_arr <- apply(
    MCMCpack::rdirichlet(N_questions, rep(alpha, N_cat)),
    FUN = cumsum,
    MARGIN = 1)[1:(N_cat - 1),]
thresholds <- sort(as.numeric(thresholds_arr))
traj <- data.frame(time = c(0, thresholds, thresholds + 1e-12, 1), score = c(max_score, max_score:1, (max_score - 1): 0, 0))

ggplot(traj, aes(x = time, y = score)) + geom_line() + time_scale

hist(thresholds)

```

